name: GAMER-XMD 
services:
  - name:GAMER-XMD 
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin

      
